// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function example_001(x) {
  return x;
}

var example = /* record */[
  /* name */"square",
  example_001
];

console.log(Curry._1(example_001, 3));

exports.example = example;
/*  Not a pure module */
